const CHANGE_BANNERS = "CHANGE_BANNERS";
const CHANGE_SONGCARD = "CHANGE_SONGCARD";
const CHANGE_NEWALBUM = "CHANGE_NEWALBUM";
const GET_ALLRANK = "GET_ALLRANK";

const ORIGINAL_RANK = "ORIGINAL_RANK";
const UP_RANK = "UP_RANK";
const NEW_RANK = "NEW_RANK";

export {
    CHANGE_BANNERS,
    CHANGE_SONGCARD,
    CHANGE_NEWALBUM,
    GET_ALLRANK,
    ORIGINAL_RANK,
    UP_RANK,
    NEW_RANK
}